apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-nginx
  name: deployment-nginx
  namespace: giropops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: deployment-nginx
    spec:
       containers:
       - image: nginx:1.18
         name: nginx
         resources:
           limits:
             cpu: "0.3"
             memory: 128Mi
           requests:
             cpu: "0.2"
             memory: 64Mi
         livenessProbe:
           tcpSocket:
             port: 80
           initialDelaySeconds: 10
           successThreshold: 1
           periodSeconds: 10
           timeoutSeconds: 5
           failureThreshold: 3
         readinessProbe:
           exec:
             command:
             - curl
             - -f
             - http://localhost:80/
           initialDelaySeconds: 10
           successThreshold: 1
           periodSeconds: 10
           timeoutSeconds: 10
           failureThreshold: 3
                